language: python
install: "pip install tox"
script: "tox -e $TRAVIS_BUILD"
python: 3.5
env: TRAVIS_BUILD=py35

matrix:
  allow_failures:
    - env: TRAVIS_BUILD=deploy
  fast_finish: true
  include:
    - python: 3.5
      env: TRAVIS_BUILD=coverage
      before_install: "pip install codecov"
      after_success: "codecov"
    - python: 3.5
      dist: trusty
      sudo: false
      env: TRAVIS_BUILD=lint
      before_install: "nvm use stable"
      script: "make lint"
    - python: 3.5
      dist: trusty
      sudo: required
      before_install: "sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils"
      install: |
        pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
        . $HOME/.nvm/nvm.sh
        nvm install stable
        nvm use stable
        pip install -e .
      script: |
        make
        make pyinstaller
        make -C gui dist
      env: TRAVIS_BUILD=deploy
    - language: node
      node_js: node
      os: osx
      install: |
        brew install python3
        pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
        pip3 install -e .
      script: |
        make
        make pyinstaller
        make -C gui dist
      env: TRAVIS_BUILD=deploy

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches
    - fava/static/node_modules
    - gui/node_modules
