build: false
version: '{build}'
platform: x64
environment:
  PYTHON: 'C:\Python36'

install:
  - '%PYTHON%\python -m pip install -U setuptools pip wheel tox'

test_script:
  - '%PYTHON%\scripts\tox -e py36'

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '.tox -> setup.py'
